# Generated by Django 3.0.8 on 2020-07-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizator',
            name='echipa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membri', to='aplicatie.Echipa'),
        ),
    ]
