# Generated by Django 3.0.8 on 2020-07-03 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0002_auto_20200703_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizator',
            name='tip_utilizator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizatori', to='aplicatie.TipUtilizator'),
        ),
    ]
